# Worksheet 04

Name:  Zhengxu Wang  
UID: U81066856  

### Topics

- Distance & Similarity
- Cost Functions
- K means

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

p is the power or degree parameter.   
d is the number of dimensions or features of the data set. 

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

Euclidean distance is the straight distance between two points, the shortest distance.  
Manhattan distance is the distance along the axis, how many steps it takes from one to another take when walking along the axis.

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

The distance similarity will less sensitive and close to Chebyshev distance.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

No. Although it is still can be calculated but it against the traingle inequality rule.

e) when would you use cosine similarity over the euclidan distance?

When the direction of a feature is more important than the stright-forward distance.

f) what does the jaccard distance account for that the manhattan distance doesn't?

The Jaccard distance considers the intersection of the sets and is more sensitive to the overlap between the sets, while the Manhattan distance does not account for the overlap and is more sensitive to the absolute differences between the elements in the sets.

#### Part 2

Consider the following two sentences:

In [1]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [2]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [3]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['hello', 'name', 'Alice', 'Bob', 'is', 'my']
[1, 1, 1, 0, 1, 1]


Let's add a new sentence to our corpus:

In [4]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [9]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['hello', 'name', 'Claude', 'Alice', 'Bob', 'hi', 'is', 'my']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [10]:
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

v2 = [1 if x in s2 else 0 for x in all_words]
print(v2)

v3 = [1 if x in s3 else 0 for x in all_words]
print(v3)

[1, 1, 0, 1, 0, 0, 1, 1]
[1, 1, 0, 0, 1, 0, 1, 1]
[0, 1, 1, 0, 0, 1, 1, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [11]:
def manhattan_distance(v1, v2):
    zipped_vecs = zip(v1, v2)
    return sum(abs(x1 - x2) for x1, x2 in zipped_vecs)

print('v1 to v2:', manhattan_distance(v1, v2))
print('v2 to v3:', manhattan_distance(v2, v3))
print('v1 to v3:', manhattan_distance(v1, v3))

v1 to v2: 2
v2 to v3: 4
v1 to v3: 4


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [12]:
import numpy as np

s4 = "hi Alice"
corpus.append(s4)
v4 = [1 if x in s4 else 0 for x in all_words]

s5 = "hello Claude"
corpus.append(s5)
v5 = [1 if x in s5 else 0 for x in all_words]

s6 = "Bob my name is Claude"
corpus.append(s6)
v6 = [1 if x in s6 else 0 for x in all_words]

s7 = "hi Claude my name is Alice"
corpus.append(s7)
v7 = [1 if x in s7 else 0 for x in all_words]

s8 = "hello Bob"
corpus.append(s8)
v8 = [1 if x in s8 else 0 for x in all_words]

matrix = []
matrix.append(v1)
matrix.append(v2)
matrix.append(v3)
matrix.append(v4)
matrix.append(v5)
matrix.append(v6)
matrix.append(v7)
matrix.append(v8)

matrix = np.array(matrix)
print(matrix)

[[1 1 0 1 0 0 1 1]
 [1 1 0 0 1 0 1 1]
 [0 1 1 0 0 1 1 1]
 [0 0 0 1 0 1 0 0]
 [1 0 1 0 0 0 0 0]
 [0 1 1 0 1 0 1 1]
 [0 1 1 1 0 1 1 1]
 [1 0 0 0 1 0 0 0]]


e) How many rows and columns does this matrix have?

In [13]:
print(matrix.shape)

(8, 8)


f) When using the Manhattan distance, which two sentences are the most similar?

In [14]:
lowest_dist = manhattan_distance(v1, v2)
most_similar = (1, 2)

for i in range(1, 9):
    for j in range(i + 1, 9):
        if manhattan_distance(matrix[i - 1], matrix[j - 1]) < lowest_dist:
            lowest_dist = manhattan_distance(matrix[i - 1], matrix[j - 1])
            most_similar = (i, j)
            
print(str(most_similar[0]) + " and " + str(most_similar[1]) + " : " + str(lowest_dist))

3 and 7 : 1


### Cost Function

Solving Data Science problems often starts by defining a metric with which to evaluate solutions were you able to find some. This metric is called a cost function. Data Science then backtracks and tries to find a process / algorithm to find solutions that can optimize for that cost function.

For example suppose you are asked to cluster three points A, B, C into two non-empty clusters. If someone gave you the solution `{A, B}, {C}`, how would you evaluate that this is a good solution?

Notice that because the clusters need to be non-empty and all points must be assigned to a cluster, it must be that two of the three points will be together in one cluster and the third will be alone in the other cluster.

In the above solution, if A and B are closer than A and C, and B and C, then this is a good solution. The smaller the distance between the two points in the same cluster (here A and B), the better the solution. So we can define our cost function to be that distance (between A and B here)!

The algorithm / process would involve clustering together the two closest points and put the third in its own cluster. This process optimizes for that cost function because no other pair of points could have a lower distance (although it could equal it).

### K means

a) (1-dimensional clustering) Walk through Lloyd's algorithm step by step on the following dataset:

`[0, .5, 1.5, 2, 6, 6.5, 7]` (note: each of these are 1-dimensional data points)

Given the initial centroids:

`[0, 2]`

cluster1: [0, 0.5]  
cluster2: [1.5, 2, 6, 6.5, 7]  

New Center 1: 0.25  
New Center 2: 4.6

Cluster 1: [0, 0.5, 1.5, 2]  
Cluster 2: [6, 6.5, 7]  

New Center 1: 1  
New Center 2: 6.5  

Cluster 1: [0, 0.5, 1.5, 2]  
Cluster 2: [6, 6.5, 7]  

New Center 1: 1  
New Center 2: 6.5  

There is no change from iteration 2 to 3, so the algorithm will end.

b) Describe in plain english what the cost function for k means is.

The cost function for k-means is a measure of how well the data points are clustered, where a lower cost function value indicates a better clustering solution. The k-means algorithm tries to minimize this cost function to produce the best clustering solution.

c) For the same number of clusters K, why could there be very different solutions to the K means algorithm on a given dataset?

Different initial center will lead to different results.

d) Does Lloyd's Algorithm always converge? Why / why not?

Yes, because it is greedy algo.